fix: update build for cunit in ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,15 +28,33 @@ jobs:
             libc6-dev \
             gawk
 
-      - name: Prepare and build CUnit
+      - name: Download and build CUnit
         run: |
-          cd lib/cunit
-          autoreconf -fi
-          [ -f configure.in ] && mv configure.in configure.ac
-          autoupdate
+            CUNIT_DIR=lib/cunit
+            if [ ! -d "$CUNIT_DIR" ]; then
+            echo "CUnit not found! Downloading and building..."
+            mkdir -p lib && cd lib
+            wget https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
+            tar -xvf CUnit-2.1-3.tar.bz2
+            mv CUnit-2.1-3 cunit
+            rm CUnit-2.1-3.tar.bz2
+            fi
 
-          ./configure CFLAGS="-O2" LDFLAGS="-lc" || (cat config.log && exit 1)
-          make -j$(nproc)
+            echo "Building CUnit..."
+            cd $CUNIT_DIR
+            autoreconf -fi
+            ./configure --prefix="$(pwd)"
+            make -j$(nproc)
+            make install
+
+            echo "CUnit compiled and installed"
+                cd lib/cunit
+                autoreconf -fi
+                [ -f configure.in ] && mv configure.in configure.ac
+                autoupdate
+
+                ./configure CFLAGS="-O2" LDFLAGS="-lc" || (cat config.log && exit 1)
+                make -j$(nproc)
 
       - name: Clone and compile MiniLibX
         run: |
